# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='body',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
