# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_edit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author_of_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='nominated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nominated_to_view_doc', to=settings.AUTH_USER_MODEL),
        ),
    ]
