# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_edit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharewith',
            name='on_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Linked_to_doc', to='posts.Post'),
            preserve_default=False,
        ),
    ]
