# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_sharewith_on_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharewith',
            old_name='on_post',
            new_name='post',
        ),
    ]
