# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170217_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_Author_of_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharewith',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharewith_Author_of_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharewith',
            name='nominated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nominated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
