# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys_to_doc', to='posts.Post'),
        ),
    ]
